#!/bin/bash

# Define the GitHub repository URL
# GITHUB_REPO="git@github.com:harmonize-tools/template_githubpage.git"
GITHUB_REPO="https://github.com/harmonize-tools/drone4health"

# Push changes to the GitHub repository
git push "$GITHUB_REPO" main
